### ISSUE TITLE
Icinga JSON not being properly accepted from Icinga

### ISSUE THREAD

**Issue by brockoffdev** [lazyfrosch/dashing-icinga#1]
Hello, relative newbie here...

I have been working to fix an unfortunate issue where my HTTP Get from Icinga is not properly bringing back the JSON it is calling.  The "icinga_status" json group is coming down fine, however when the get request reaches "status" => "service_status"/"host_status", the content no longer render properly: 

```
"status": {
"service_status": [

]
}
}
```

I have verified the actual URL works to pull the JSON via both HTTParty and via Chrome, but something is blocking it on either the Thin/Rails side of things.  I know that the gems are not an issue, however, as I have other instances of JSON being brought down properly.

Thanks!

**Comment by lazyfrosch** [comment]
Are there any errors? And have you configured the actual url and account data in the config.ru?

**Comment by brockoffdev** [comment]
Hey @lazyfrosch, sadly no errors, and yes the account data is configured properly.

The actual issue seems to stem from the call being made itself though.  Interestingly, the call made via the browser, as I said, works fine.  However when I curl and/or run the API call via the Dashing plugin, the JSON is not properly brought in.  Having tried several different HTTP headers via curl to see if the problem may have been related to a HTTP header not being properly forwarded (both on Ubuntu and OSX), I have come to the conclusion the issue may in fact have to do with limiting on Icinga's side.  If you have any suggestions and could point me in the right direction I'd appreciate it.  However, this does not seem to be the fault of your widget(s), or Dashing. 

Thanks!

**Comment by lazyfrosch** [comment]
I cannot reproduce the problem, I would need details outputs of errors, contents and such.
