### ISSUE TITLE
Don't work with Icinga2

### ISSUE THREAD

**Issue by nioupola** [lazyfrosch/dashing-icinga#4]
Hi,

I like your dashling but I can't use it with Icinga2. I tried with another dashling (https://github.com/Icinga/dashing-icinga2) who uses API and it's work.

```
#config.ru
set :icinga_cgi,  'http://localhost/cgi-bin/icinga/'
set :icinga_user, 'icingaadmin'
set :icinga_pass, 'password'
```

**Comment by lazyfrosch** [comment]
Yep, thats made by a colleague of mine, I'm not really using Dashing anymore :)

**Comment by nioupola** [comment]
OK. Thanks for the reply. What do you use ?

**Comment by lazyfrosch** [comment]
Nothing currently, I made that dashboard for a customer.

**Comment by nioupola** [comment]
Ok. Thanks. I try to work with Icinga2.

**Comment by lazyfrosch** [comment]
Feel free to build something out of mine, thats why its open source :)
