### ISSUE TITLE
check_mk - nagios

### ISSUE THREAD

**Issue by epik0r** [lazyfrosch/dashing-icinga#5]
Hi, 

is there any clue to get it running with check_mk with nagios backend also? 
The nagios version we got has no json output (excepting statusjson.cgi with nagios 4x), but may be it's possible with check_mk somehow? 

Thanks!

**Comment by lazyfrosch** [comment]
This project is a bit older and no longer maintained.

See https://github.com/Icinga/dashing-icinga2 for a newer version.

I personally have no interest in check_mk. You might be able to use it, but this code works with the Icinga 1 CGIs and their JSON interface.

**Comment by epik0r** [comment]
Thanks a lot!
